---
title: "TopGO"
output: html_document
date: "2023-12-11"
---

TopGO
```{r}
library(topGO)

geneID2GO <- readMappings(file="TopGo_input_rn2.tsv", sep = "\t", IDsep = ",")
geneUniverse <- names(geneID2GO)
geneUniverse

cDE_cont_genes <- read.table("relaxation_selection_IDs.txt",header = FALSE)
cDE_cont_genes <- as.character(cDE_cont_genes$V1)

geneList <- factor(as.integer(geneUniverse%in%cDE_cont_genes))
names(geneList) <- geneUniverse

myGOdata <- new("topGOdata",description="relaxation_selection", ontology="MF",allGenes=geneList, annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(myGOdata, algorithm = "weight01", statistic="fisher")
resultFisher

allRes <- GenTable(myGOdata, raw.p.value = resultFisher, classicFisher = resultFisher, orderBy = "classicFisher", ranksOf = "classicFisher", topNodes = 15,numChar=1000)
allRes

write.table(allRes, file = "relaxed_of_selection_MF_weight01.txt", sep = "\t", quote = FALSE, row.names = F)
```
Visualization
Adapted from Kevin Blighe script available at https://www.biostars.org/p/471549/
```{r}
require(ggplot2)
library(scales)
library(ggpubr)

ggdata <- subset(allRes, classicFisher < 0.1 & Annotated > 1)
ggdata <- ggdata[order(ggdata$classicFisher), ]
ggdata$Term[5] <- "mitochondrial electron transport\ncytochrome c to oxygen"
ggdata$Term[12] <- "deadenylation-dependent decapping\nof nuclear-transcribed mRNA"
ggdata

ggdata$Term <- factor(ggdata$Term, levels = rev(ggdata$Term)) # fixes order
gg4 <- ggplot(ggdata,
  aes(x = Term, y = -log10(as.numeric(classicFisher)), size = (as.numeric(Significant)), fill = -log10(as.numeric(classicFisher)))) +

  expand_limits(y = 1) +
  geom_point(shape = 21) +
  scale_size(range = c(2.5,12.5), name = "Significant genes") +
  scale_fill_continuous(low = 'purple4', high = 'yellow3', name = "-log10(Fisher's exact test)") +

  xlab('') + 
  ylab('') +
  labs(
    title = 'Relaxed selection') + 
    #subtitle = 'Top 15 terms ordered by Fisher\'s exact test  p-value',
    #caption = 'Cut-off lines drawn at equivalents of p=0.2, p=0.05, p=0.001') +

  geom_hline(yintercept = c(-log10(0.2), -log10(0.05), -log10(0.001)),
    linetype = c("dotted", "longdash", "solid"),
    colour = c("black", "black", "black"),
    linewidth = c(0.5, 0.5, 0.5)) +

  theme_bw(base_size = 18) +
 theme(
    legend.position = 'right',
    legend.background = element_rect(),
    plot.title = element_text(angle = 0, size = 14, face = 'bold', vjust = 1),
    plot.caption = element_text(angle = 0, size = 10, face = 'bold', vjust = 1),
    axis.text.x = element_blank(),  # Remove x-axis labels
    axis.ticks.x = element_blank(),  # Remove x-axis ticks
    axis.text.y = element_text(angle = 0, size = 10, face = 'bold', vjust = 0.5),
    axis.title = element_text(size = 10, face = 'bold'),
    axis.title.x = element_text(size = 10, face = 'bold'),
    axis.title.y = element_text(size = 10, face = 'bold'),
    axis.line = element_line(colour = 'black'),
    #Legend
    legend.key = element_blank(), # removes the border
    legend.key.size = unit(0.5, "cm"), # Sets overall area/size of the legend
    legend.text = element_text(size = 10, face = "bold"), # Text size
    title = element_text(size = 10, face = "bold")) +
  coord_flip()

gg4
figure <- ggarrange(gg1, gg2, gg3, gg4,
                    labels = c("A","B","C","D"),
                    ncol = 2, nrow = 2)
figure
ggsave("GO_Enrichment_all1.png", width = 16, height = 10)
```

```{r}
#Get all the genes in your significant GO TERMS
#From: https://datacatz.wordpress.com/2018/01/19/gene-set-enrichment-analysis-with-topgo-part-1/

myterms = allRes$GO.ID 
mygenes = genesInTerm(myGOdata, myterms)
mygenes

var=c()
for (i in 1:length(myterms))
{
myterm=myterms[i]
mygenesforterm= mygenes[myterm][[1]]
mygenesforterm=paste(mygenesforterm, collapse=',')
var[i]=paste("GOTerm",myterm,"genes-",mygenesforterm)
}
write.table(var,"genesSignificanTerms.txt",sep="\t",quote=F)

```
